// import { ChainId } from '@pancakeswap-libs/sdk';
import { ChainId } from '@spookyswap/sdk';
import { Configuration } from './tomb-finance/config';
import { BankInfo } from './tomb-finance';

const configurations: { [env: string]: Configuration } = {
  production: {
    chainId: ChainId.MAINNET,
    networkName: 'Fantom Opera Mainnet',
    ftmscanUrl: 'https://ftmscan.com',
    defaultProvider: 'https://rpc.ftm.tools/',
    deployments: require('./tomb-finance/deployments/deployments.mainnet.json'),
    externalTokens: {
      WFTM: ['0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', 18],
      FUSDT: ['0x04068DA6C83AFCFA0e13ba15A6696662335D5B75', 6], // This is actually usdc on mainnet not fusdt
      BOO: ['0x841FAD6EAe12c286d1Fd18d1d525DFfA75C7EFFE', 18],
      ZOO: ['0x09e145a1d53c0045f41aeef25d8ff982ae74dd56', 0],
      SHIBA: ['0x9ba3e4f84a34df4e08c112e1a0ff148b81655615', 9],
      BELUGA: ['0x4A13a2cf881f5378DEF61E430139Ed26d843Df9A', 18],
      BIFI: ['0xd6070ae98b8069de6B494332d1A1a81B6179D960', 18],
      MIM: ['0x82f0b8b456c1a451378467398982d4834b6829c1', 18],
      'wFTM': ['0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83', 18],
      '2OMB': ['0x7a6e4e3cc2ac9924605dca4ba31d1831c84b44ae', 18],
      '2SHARES': ['0xc54a1684fd1bef1f077a336e6be4bd9a3096a6ca', 18],
      'USDT-FTM-LP': ['0x2b4C76d0dc16BE1C31D4C1DC53bF9B45987Fc75c', 18],
      'TOMB-FTM-LP': ['0x2A651563C9d3Af67aE0388a5c8F89b867038089e', 18],
      'TSHARE-FTM-LP': ['0x4733bc45eF91cF7CcEcaeeDb794727075fB209F2', 18],
    },
    baseLaunchDate: new Date('2021-06-02 13:00:00Z'),
    bondLaunchesAt: new Date('2020-12-03T15:00:00Z'),
    masonryLaunchesAt: new Date('2020-12-11T00:00:00Z'),
    refreshInterval: 10000,
  },
};

export const bankDefinitions: { [contractName: string]: BankInfo } = {
  /*
  Explanation:
  name: description of the card
  poolId: the poolId assigned in the contract
  sectionInUI: way to distinguish in which of the 3 pool groups it should be listed
        - 0 = Single asset stake pools
        - 1 = LP asset staking rewarding TOMB
        - 2 = LP asset staking rewarding TSHARE
  contract: the contract name which will be loaded from the deployment.environmnet.json
  depositTokenName : the name of the token to be deposited
  earnTokenName: the rewarded token
  finished: will disable the pool on the UI if set to true
  sort: the order of the pool
  */
  Tomb2sharesRewardPool: {
    name: 'Earn 3OMB by staking 2SHARES',
    poolId: 0,
    sectionInUI: 0,
    contract: 'Tomb2ShareRewardPool',
    depositTokenName: '2SHARES',
    earnTokenName: '3OMB',
    finished: false,
    multiplier: '7500',
    site: "https://2omb.finance",
    buyLink: 'https://spookyswap.finance/swap?outputCurrency=0x7a6e4e3cc2ac9924605dca4ba31d1831c84b44ae',
    sort: 1,
    closedForStaking: false,
  },
  Tomb2ombRewardPool: {
    name: 'Earn 3OMB by staking 2OMB',
    poolId: 0,
    sectionInUI: 0,
    contract: 'Tomb2ombRewardPool',
    depositTokenName: '2OMB',
    earnTokenName: '3OMB',
    finished: false,
    multiplier: '5000',
    site: 'https://2omb.finance',
    buyLink: 'https://spookyswap.finance/swap?outputCurrency=0x7a6e4e3cc2ac9924605dca4ba31d1831c84b44ae',
    sort: 2,
    closedForStaking: false,
  },
  TombBelugaRewardPool: {
    name: 'Earn 3OMB by staking BELUGA',
    poolId: 0,
    sectionInUI: 0,
    contract: 'TombBelugaRewardPool',
    depositTokenName: 'BELUGA',
    earnTokenName: '3OMB',
    finished: false,
    multiplier: '500',
    site: 'https://beluga.fi',
    buyLink: 'https://beets.fi/#/trade/0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83/0x4A13a2cf881f5378DEF61E430139Ed26d843Df9A',
    sort: 3,
    closedForStaking: false,
  },
  TombBifiRewardPool: {
    name: 'Earn 3OMB by staking BIFI',
    poolId: 1,
    sectionInUI: 0,
    contract: 'TombBifiGenesisRewardPool',
    depositTokenName: 'BIFI',
    earnTokenName: '3OMB',
    finished: false,
    multiplier: '500',
    site: 'https://app.beefy.finance/#/fantom',
    buyLink: 'https://beets.fi/#/trade/0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83/0xd6070ae98b8069de6B494332d1A1a81B6179D960',
    sort: 4,
    closedForStaking: false,
  },
  TombWrappedFtmRewardPool: {
    name: 'Earn 3OMB by staking WFTM',
    poolId: 2,
    sectionInUI: 0,
    contract: 'TombWrappedFtmRewardPool',
    depositTokenName: 'wFTM',
    earnTokenName: '3OMB',
    finished: false,
    multiplier: '500',
    site: 'https://fantom.foundation',
    buyLink: 'https://ecoswap.exchange',
    sort: 5,
    closedForStaking: false,
  },
  TombMimRewardPool: {
    name: 'Earn 3OMB by staking MIM',
    poolId: 3,
    sectionInUI: 0,
    contract: 'TombMimGenesisRewardPool',
    depositTokenName: 'MIM',
    earnTokenName: '3OMB',
    finished: false,
    multiplier: '500',
    site: 'https://abracadabra.money/',
    buyLink: 'https://ftm.curve.fi/factory/7',
    sort: 6,
    closedForStaking: false,
  },
  TombFtmLPTombRewardPool: {
    name: 'Earn TOMB by TOMB-FTM LP',
    poolId: 0,
    sectionInUI: 1,
    contract: 'TombFtmLpTombRewardPool',
    depositTokenName: 'TOMB-FTM-LP',
    earnTokenName: 'TOMB',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 7,
    closedForStaking: true,
  },
  TombFtmLPTombRewardPoolOld: {
    name: 'Earn TOMB by TOMB-FTM LP',
    poolId: 0,
    sectionInUI: 1,
    contract: 'TombFtmLpTombRewardPoolOld',
    depositTokenName: 'TOMB-FTM-LP',
    earnTokenName: 'TOMB',
    finished: true,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 9,
    closedForStaking: true,
  },
  TombFtmLPTShareRewardPool: {
    name: 'Earn TSHARE by TOMB-FTM LP',
    poolId: 0,
    sectionInUI: 2,
    contract: 'TombFtmLPTShareRewardPool',
    depositTokenName: 'TOMB-FTM-LP',
    earnTokenName: 'TSHARE',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 8,
    closedForStaking: false,
  },
  TshareFtmLPTShareRewardPool: {
    name: 'Earn TSHARE by TSHARE-FTM LP',
    poolId: 1,
    sectionInUI: 2,
    contract: 'TshareFtmLPTShareRewardPool',
    depositTokenName: 'TSHARE-FTM-LP',
    earnTokenName: 'TSHARE',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 9,
    closedForStaking: false,
  },
  Tomb2SHARESRebates: {
    name: 'Bond 2SHARES, earn 3OMB',
    poolId: 0,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: 'WFTM',
    earnTokenName: 'TOMB',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 1,
    closedForStaking: false,
  },
  Tomb2SHARESFTMRebates: {
    name: 'Bond 2SHARES-WFTM LP, earn 3OMB',
    poolId: 1,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: 'BOO',
    earnTokenName: 'TOMB',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 2,
    closedForStaking: false,
  },
  Tomb3OMBFTMRebates: {
    name: 'Bond 3OMB-WFTM LP, earn 3OMB',
    poolId: 3,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: 'ZOO',
    earnTokenName: 'TOMB',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 3,
    closedForStaking: false,
  },
  Tomb3SHARESRebates: {
    name: 'Bond 3SHARES, earn 3OMB',
    poolId: 2,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: 'SHIBA',
    earnTokenName: 'TOMB',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 4,
    closedForStaking: false,
  },
  Tomb3SHARESFTMRebates: {
    name: 'Bond 3SHARES-WFTM LP, earn 3OMB',
    poolId: 3,
    sectionInUI: 3,
    contract: 'TombFtmRewardPool',
    depositTokenName: 'ZOO',
    earnTokenName: 'TOMB',
    finished: false,
    multiplier: '0',
    buyLink: '',
    site: '',
    sort: 5,
    closedForStaking: false,
  },
};

export default configurations['production'];
